###############################################################
#
# Miguel LópezG · Technical Challenge
# Challenge #02 . Platform Challenge
# Questions 2.8 . Write a Terraform template that provisions
#                 PostgreSQL DB and a VPN in a VNet
#
# 2023/01/28
# Module outputs
# ##############################################################

output "rg_name_out" {
    description = "Output variable: Resource group name generated by the deployment"
    value       = azurerm_resource_group.rg.name
}

output "rg_location_out" {
    description = "Output variable: Resource group location generated by the deployment"
    value       = azurerm_resource_group.rg.location
}

output "stg_act_name_out" {
    description = "Output variable: Storage account name generated by the deployment"
    value       = resource.azurerm_storage_account.stmgmnt.name
}